---
creation_rules:
  - path_regex: infrastructure/.*\.sops\.yaml
    key_groups:
      - age:
          - age19ay5dn0m46ya06gt2nwxk0mfcfvu2f3e66gadldnn3k06p7ys3gs25jfev
  - path_regex: kubernetes/.*/secret-.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age19ay5dn0m46ya06gt2nwxk0mfcfvu2f3e66gadldnn3k06p7ys3gs25jfev
  - path_regex: kubernetes/.*\.sops\.yaml
    key_groups:
      - age:
          - age19ay5dn0m46ya06gt2nwxk0mfcfvu2f3e66gadldnn3k06p7ys3gs25jfev
  - path_regex: kubernetes/.*\.sops\.ini
    key_groups:
      - age:
          - age19ay5dn0m46ya06gt2nwxk0mfcfvu2f3e66gadldnn3k06p7ys3gs25jfev
  - path_regex: kubernetes/.*\.sops\.toml
    key_groups:
      - age:
          - age19ay5dn0m46ya06gt2nwxk0mfcfvu2f3e66gadldnn3k06p7ys3gs25jfev
  - path_regex: kubernetes/.*\.sops\.json
    key_groups:
      - age:
          - age19ay5dn0m46ya06gt2nwxk0mfcfvu2f3e66gadldnn3k06p7ys3gs25jfev
  - path_regex: kubernetes/.*\.sops\.env
    key_groups:
      - age:
          - age19ay5dn0m46ya06gt2nwxk0mfcfvu2f3e66gadldnn3k06p7ys3gs25jfev

