---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-vaultwarden-database
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/security/vaultwarden/database"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  decryption:
    provider: sops
  dependsOn:
    - name: cluster-apps-cloudnative-pg
    - name: cluster-apps-rook-ceph-cluster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-vaultwarden
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/security/vaultwarden/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  decryption:
    provider: sops
  dependsOn:
    - name: cluster-apps-vaultwarden-database
    - name: cluster-apps-smtp-relay
