---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cloudnative-pg
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/datastore/cloudnative-pg/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  decryption:
    provider: sops
  postBuild:
    substituteFrom: []
