apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: security
stringData:
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:6NECBeh+vOKCtV70axj1Wofy10VQ7mc=,iv:n2pFRvnQ+BqH6OTVdFkPT3YdlqS6F5MkVzdNPW2fO08=,tag:Lm8TcoNBBpcIVJErDeJHDA==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:6uToWy+VOcqaQasEd8IkZsOPs7cTXU3jM41eLbTB1gieHhB7CL76ES2G2VNbHWkmAoSmlcPoErQ=,iv:CW8/pAHBeh+ffVoxxm6OBxLXSl0grmYcCWJawR9wftc=,tag:BYHif9ktUKQslkZRYCquCA==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:aYee3sJSFp4xIhUf6ufm8q4RIgwFXSJEV8c4yJOYMqzs+OMrPDNcMf4/FNpAjv2zWrU2Mg==,iv:T9ePwA30uc+aPU99feoNXsMuWugXAr8ASl2iTRsjJv8=,tag:cxizyMndyhCjnyNq3TLHxw==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:9l+fVjf+cJ9aPwihwzPicjiDFQP05gAmoUpzG8Kk+TzngIWiNDN8Irw8Epma/Xs7pIY=,iv:K81OvHuIxJATixxFcc8Ve0HWMKxlbTUgbWHByvyoTrQ=,tag:vUudIFePLsiQtC5HT/TKyQ==,type:str]
    AUTHENTIK_PLEX_CLIENT_ID: ENC[AES256_GCM,data:TczsW3dizBd0hooAdpsocyNzPVZH5FPxQPHxVqbTljJaMhMhfcnbf9KCdhxGHQsnJg7EuA==,iv:DSYacNIHk26UmcIB2iOBj+vOlZZZ942rBuLS5CNNMfo=,tag:C8GCX0RufqYLhP/nX8l2Hw==,type:str]
    AUTHENTIK_PLEX_TOKEN: ENC[AES256_GCM,data:4L/pahZofgkp5fx5vXTVjjHbm5c=,iv:l4iWsG9MavTL1kZbwiwa5MNh65f+RUgcee4NgLaQPlM=,tag:VD6hQJruH+ugaymgWDWppw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/dco-main/locations/global/keyRings/dyckshaus-keyring/cryptoKeys/sops
          created_at: "2024-01-26T04:27:12Z"
          enc: CiQA0oL7B7F2iP8+nbcrUOmTJe0mK31Ehzezt7Y9+QtVlngtfssSSQApFo36vxgxz/EGuH7ix8/C0qphZSS9qtJwDIvtboJqLD5y/+yA9qbFp++7OaOLcSzc4pI9uOonG6KwlDB6YIvunfWXTGvgMPE=
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ay5dn0m46ya06gt2nwxk0mfcfvu2f3e66gadldnn3k06p7ys3gs25jfev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaEc5SEhzRnFNekpHaG53
            ZVN4a3lkN0R5bUswQ2xhQUFEd21wTUFzUlNFCnVoSFdrZ0RaZ3dnTGRJS3JJQU9L
            cEx5N3ZoeC9YczNFUHZ6amtZUlhTUncKLS0tIHZkNnF6NmFnYUcvY1VqZlhPZlBK
            Q1JhK1ROQWphVW4rc21JQXhlNFMrK28KhWg7TOua7ReNTthyXLaSZxMnJ2bzcfwd
            f3jDLPqqkQSe7NW2/MEzXHhXJs0qgsPDJy6rH3YmIftmhUPvfpENMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-11T01:27:03Z"
    mac: ENC[AES256_GCM,data:kVZ/866mabRLhFqEsBlK4bhcIA2yQSUTRzwQW5HmwLbxTOnBojU8FjDH6LDGW5mBZYMBxkDf7QAjc/A3OGRCOGX2qKBndGOtwCjNKdgpLF8GTUYZTS9Rfvz406lpnpyB17WZ8V4cmmCgpLz/MXpE5lMmziXpvtP9WA0G/aOTyhU=,iv:LNP5HtJph/KGi7VjBU5es4a4DKg6kWkpMWOTJNfsihA=,tag:gODABrm4hIZkGulCmgGx0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
