apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: monitor
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: true
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: flux-system
stringData:
    GF_AUTH_GENERIC_OAUTH_API_URL: ENC[AES256_GCM,data:+Web/byxZb36mbXQktMODDmE1GiK0kOX11rMyCp3HFANIU4tnRfQNCI2mAB482EJZUo=,iv:1lptw73Z7ctKFwusV9tuGJs8Jld3D6laSxu7H7nC6i0=,tag:m0yKJq1/iADypbohkKSUnA==,type:str]
    GF_AUTH_GENERIC_OAUTH_AUTH_URL: ENC[AES256_GCM,data:Se8rJypnvBdXF4wpi9cQVdMAnL9+ryhBBY/D6te7mdWyh8lYevdKj7KEe0WlAV58Il6I,iv:T2Hh6DbHf9nCM9NqHZL5WJJEQWEi4WeeZY6G3K/KDMY=,tag:eRhQBZGfHlsiZuq9dMqTyg==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:uU/+VIyzPA==,iv:xVWNXAmSGiGY5L5FhvG+ygLF3JvBF4fYUG/RChBXreA=,tag:SOJyT/iMBxeH6IjfoiDuUg==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:woZD6r3GEbUY8f2TxIMYcsvztGcU8hJTGUt7EdXrjKQV4eTkDfQBljuifjZUL4dVbGXew/AW945uzhS45x6ze5aHm638Bnjk+MnSNsCs,iv:vQCe8NpAPeOmK8h5XVWwVSaR5uF3qtwX5La7KxSrz20=,tag:Mdce+6H74bYXWH//aZK2/g==,type:str]
    GF_AUTH_GENERIC_OAUTH_TOKEN_URL: ENC[AES256_GCM,data:Hj3YY+wtsO10r5/dan2NEXcvdANCKpqwDQVOiD351F2l7uQGhYeYf8KNszVFw3o=,iv:rot58LgUbGYF5gq+0bSx8/uVOt/je4QNuuZuE2Z0tfs=,tag:aWDSNinZCHIyZL2PFNGkiQ==,type:str]
    GF_AUTH_SIGNOUT_REDIRECT_URL: ENC[AES256_GCM,data:TMvVMlb+Tr2J9sHOWIIAxCDDf5D302HbyT8EaPpO3EbrI2pHszlM/OZYRf158PocPcji57Cd7n/FW1tkag==,iv:OBdDQ4IOu21v1fhtbiqLYqUGAP2glF80HWdTkE29Vgc=,tag:3ePvJFC7xC+zk3K1y1KHQg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/dco-main/locations/global/keyRings/dyckshaus-keyring/cryptoKeys/sops
          created_at: "2024-02-11T01:43:14Z"
          enc: CiQA0oL7B36fndX22gT2Opk53impAneeaIgheB5Z0d6euyeJqYISSAApFo36eH8JQVP+dPA5Bi1/GhUCBz+2TAJKX/sDTTkRnmR7RhLvHBc+esBtlgy+s63/ESEJpmqI9CK4ki0inveIl/eLzXH24Q==
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ay5dn0m46ya06gt2nwxk0mfcfvu2f3e66gadldnn3k06p7ys3gs25jfev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0T21ydDB2TkZSS2Q0ZkJ4
            UFFraDdVdW0wVWI5ZmVaQkRvMkRyZ0d3UUNNCkI4RWsxNTB5azBBbzdXYkUvT1My
            SWwrbjdrd2VVa013TE5iQk1DcWtrbDgKLS0tIGhjbFUxM3A5Z0dLZXR6YVZ2Wlho
            VDZqMzFPQTdvdCtPS041V2VrVWpwL2sKYdMjXPbf5mUV8+S5aeFeBopXY7ijxw8i
            rQazCsG2YIUoMe02UoQ37o2E2yIL9YZ+tyx3X8c6fcF4Fwho4TrMAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-11T01:43:14Z"
    mac: ENC[AES256_GCM,data:YCY1/NRt8hWb5QzvlsxWP6k+3YxuI6X+8IVJ7me/hTpYmx5HoB2GSXvQZfLxfdGR1PoMoUByt8TVaZlJAdazo73XNY2THNLJSw+o4qgQz7s+BIbstoBxuN2YmpR/0kPP2bn+R7dbcSat33J3DMu33IMwBSFket+2PPJF4OjgXEI=,iv:prTf2qBEegqsazTKl8ANcQBkXPTJVJXDGuYuYH/AQn8=,tag:lBwHNcDAR47r26r+kU4UKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
