apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media
spec:
  storageClassName: media
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SYNOLOGY_ADDR}
    path: "/volume1/FileServer/_Media"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
