---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CLUSTER_NAME: k8s-001
  CLUSTER_APISERVER_ENDPOINT: 10.0.0.10
  SYNOLOGY_ADDR: 10.10.1.10
  TRUENAS_ADDR: 10.10.20.5

  SVC_NGINX_EXTERNAL_ADDR: 10.77.0.10
  SVC_NGINX_INTERNAL_ADDR: 10.77.0.20
  SVC_HASS_ADDR: 10.77.0.42
  SVC_MASS_ADDR: 10.77.0.62
  SVC_MQTT_ADDR: 10.77.0.67
  SVC_PLEX_ADDR: 10.77.0.79
  SVC_VPN_ADDR: 10.77.0.77
  SVC_SMTP_RELAY_ADDR: 10.77.0.25
  WHITELIST_IP_RANGE: "10.0.0.0/8, 192.168.0.0/16, 172.22.0.0/15"
