---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-music-assistant
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/media/music-assistant/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home-ops
  wait: true
  postBuild:
    substituteFrom: []
  decryption:
    provider: sops
  dependsOn:
    - name: cluster-apps-rook-ceph-cluster
