apiVersion: v1
kind: Secret
metadata:
    name: plex-secret
    namespace: media
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: security
stringData:
    PLEX_CLAIM: ENC[AES256_GCM,data:HnX+KhvaQJ570lRJAxEccytbBPJRzooXdHg=,iv:KkwoHfUF7qRim1P01sGRXkXPO/Xb/TuG96wI4dy9MFM=,tag:kbPJURL+divYraAdEK9gfQ==,type:str]
    PLEX_SERVER_ID: ENC[AES256_GCM,data:Zr2E5BgsHqTB1sZhxzbCxBxDVq1YVxwT0e9ZP5QwEFUpUWyR,iv:Yx/AcbNlT/LyYejxANtOFd9sztznlfap6iuTKZxDj5M=,tag:ffCpmYT+G5YTLShLiEA4Bw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/dco-main/locations/global/keyRings/dyckshaus-keyring/cryptoKeys/sops
          created_at: "2024-01-26T05:53:50Z"
          enc: CiQA0oL7BxPdwazZ6kXkn47ce0teysdhZCYHys5A5igbLVyb/HcSSQApFo36HRUTvnIbFD+FeSrN63WH0dyOZRPHUOk95EKxD7GxQVgoNuSLDci69PAZLKgeFOrarqaWg86C4XeCxvOCJCBpfEzr9+I=
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ay5dn0m46ya06gt2nwxk0mfcfvu2f3e66gadldnn3k06p7ys3gs25jfev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcTdNVTBiOG9laHR6cEo3
            LytrR1JGdzBseFpWNVFFakVYRGpSU3lFNkQwCjVYejluMXF3Tlh5TENGM3c4WmN5
            ME5YRndubkQxeVdKZHZUR0FyWGJySncKLS0tIG9CUUNjS1BsVWUybERJemdOazhl
            SlMrbEZzaXdHYnJUZjZ3YkJwV2oyRWcKF277g0XnyLohAj4uoZhxJRfOGw5FBcLE
            jijwBWEhJVRuAE9iEmvUVbMOXWJ08U/4J6oh54OuN4EtxuQmw4tU6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-18T22:14:48Z"
    mac: ENC[AES256_GCM,data:5dExGGjACYQv5jK5+n5s+m7k1uh8dIjnxbqHb/nZLkkF2Dv0gHZsKF3IB03HsS2UVbXf/eaapV4boOW9n0HXBs+WjtCX/vg7pNEwjl3+ryaLMtLm4RTazKb+z29u1bUWHV4auuQZvPVaDolIPKjLrQt5nBgDT4gZws9MW5MSG1c=,iv:XzkCWksUor/r+bU0Zq6es8+y4A/W+VQ4fjO2Qw/o2vY=,tag:5EYnUIaOxBO3yBLBk5eURw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
