apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: datastore
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: security,home
stringData:
    AWS_SECRET_ACCESS_KEY_ID: cnpg-access-key
    AWS_SECRET_ACCESS_KEY: llFVfUmIitQx2teqlbGrUgjUtxFhHluqjg1ptmCm
