apiVersion: v1
kind: Secret
metadata:
    name: starr-apps-secret
    namespace: media
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: download
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:l3Kgzrq9Qqr4NMXimzWS/elaEvWtk2S7mguzXtEcXX8=,iv:mnTW7SPEpcWGb4cyt9VbeXie8roO+NbJ6cqT/s6qBdw=,tag:U7igFyGARI7FKAUPK8b2vw==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:YxnelMpET+8x96cyspe6hzKnfBdbLdyxwIlJ1sUqk8E=,iv:KaVVSMZ6duzWejEDrNQ59ORKJIW4sMqdBzIySlvayVE=,tag:srZ0F5D+kkcE+Z+lwRqzAg==,type:str]
    LIDARR_API_KEY: ENC[AES256_GCM,data:DlJvEsVQ1LpGkYK+P3m7TD2nyxGl/7cSE4i7WeVVGqM=,iv:5hJMBWW2+JruwgNGOkIxg2Xur4g8nAcClLY352Paqxw=,tag:OQBWUN+ehKd4idG6Vrqqug==,type:str]
    READARR_API_KEY: ENC[AES256_GCM,data:pBbQYahiouRV8nGeO2CVoRwEzucLMuYcGD6RbuDZCQs=,iv:12thwNRVb8yTr9INI0g8VZWat5n27J47pQp/hVwLmX4=,tag:IEVHAvVrfPjaNUDbOgj+eA==,type:str]
    BAZARR_API_KEY: ENC[AES256_GCM,data:R+/0bNOhhQkztBhCgbNqB14JlzHXQ4ZGO5uu6OMt9Xo=,iv:Bj/KuM6AXOeksM3WyQAcRX7Gmijnx9D/FPul1stwVTA=,tag:DHU9NW2JU3Dj2vvakYz8zg==,type:str]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:93TZa/fXIPMF6ojjIJ5ZAK/aNboecLE/cZiU0USZbLU=,iv:t+YhxqGpFrSM+mKf+uV2VqUmuIe9Qefobwb+hxhx0qM=,tag:n9M6pofqJ2X9horFCHll3Q==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/dco-main/locations/global/keyRings/dyckshaus-keyring/cryptoKeys/sops
          created_at: "2024-01-26T05:20:54Z"
          enc: CiQA0oL7B1c8ySe7Vapl4UU4JK2C/6Lykinlq3hti3lS+1osqwoSSQApFo36cdq37dl1DUBmTgs0dScbb1re2819jDwLgXmiSMQ3jOTLRTkBSxEP3Nqz2YEQMw12r/ztuCF4iCLOEvVOUXpPfOuCyM4=
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ay5dn0m46ya06gt2nwxk0mfcfvu2f3e66gadldnn3k06p7ys3gs25jfev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNmwyS1ByQUlCM0JjRDJI
            Q0c1UjVxR0o3QmpyR0ZxRkgxOHpZNnQ4cDFVCkhRS0RhUi9CU0ZlTi8reXQ1K2U1
            ZmNJOHBnTXVQdUpJUm14RjNjaUpMbG8KLS0tIFZzNHdTVUcyQ1B4Yk4yRURJQy9D
            Qi9sNWU3d2d6d0F0T2lmUktMQklCenMKlXgktsXdRDqiCXtsQQ1AruObBJ4Fc1eA
            SNB9YkWvVlg/ygN59cC275edM4mOX6UxdTKJiMmeuAHLQdG4xxXrYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-26T05:20:54Z"
    mac: ENC[AES256_GCM,data:M2Raawe9A5X9sU14JftHCHfeAR79JAwxtwFpF/hEJQPvjSo1AgrqrGVAutp4GiOi5CQ3m7scOJR734s3XIYn4ZOisxrthNT1HFZb9bNtz1J8wo1N0zw6iKGzX8AZvgpFc8BUXYO0AfRoFvJKkiJR/MfYSUI2MzHWy7p9D3hC754=,iv:ZsuK7TKXtT+AXrQU89W28skl4eZoRJaacYBmexgwEfc=,tag:5QMVujn1DfKAA+tHFH/joA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
