apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: security
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: network
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:VUrsB3NTrdP6QUrul7lxKwOczLBPoh2lT1l1LNnJHFeIPIXkui1+cA==,iv:sJyAfApRbuRmzxtiYbOfcOXygZEeRjgmS5LJyljvVUU=,tag:yHmEe+z3MD8T3T18bmWb2w==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/dco-main/locations/global/keyRings/dyckshaus-keyring/cryptoKeys/sops
          created_at: "2024-01-22T23:29:51Z"
          enc: CiQA0oL7B4OMbPko7ugSJez6p+FvDxLOKkxffZDJamzvbXQB094SSQApFo36/RkbWjXMCQoTdzQCXnp3FA/XvsIj7RPMt1G402LsqKvzhWF6g+eJXGkSmBbSgFrTE+ajcfam2sOlvq30CRdZil0oK78=
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ay5dn0m46ya06gt2nwxk0mfcfvu2f3e66gadldnn3k06p7ys3gs25jfev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUW1KUWFUM2pxYW9PcVQv
            dnQ5S3ZiaWNiN2RDa1pzdDc1SVB5eHRYS0RjClZlRkF2MzE0VGw5bGQ0VlpXS2N4
            bm9DbnV1cTR0MDU2RnFteGNETktWQ3cKLS0tIHgzTnJDVVgyMXIwNXlvTGxNZ1RT
            S3RDVG9mNUp1bmNuU2N1LytCKzBJdzQKEidbAgJAFNfRCqu01cM29FJKAvG9+HK9
            SDq/mQEYXs1cV+Nnx2VzuBvQkqeKj/e5MuSBd4l1xdJX1tTYUbVIxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-24T00:05:13Z"
    mac: ENC[AES256_GCM,data:5ETVJ4K58ooWoEoZczEy6B6LxNJLG1M700cUHVKnr1jJmAyPKjpf+//x/+vYVAO3ATZIxMwBvD4CuukKGzvy+Ye95wQjFKHUr2R56Nsfq7igF3qh0hnsCzQvc5Qbi4uLwRHgCj085jrj1Om7VEKCapa9NT7UsELbsqt4mFXPoPM=,iv:rwZunFtszs9LpbUF9wxfO9JQb5C2PNk4/6MCREiFJOM=,tag:7xDQiCAayj3dyPG0tYgI7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
