apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: security
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: network
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:wVTC4EtIty5hHrOVH33mrRmj+F7ymSkL3RkqpraJMyXzCQjmqw==,iv:pVsqYNcm0DKidwufI5zxj/1S4g3ylzfD/xWpfAzqkLY=,tag:AtDLkGPqbfSR7VyvN0qDcg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/dco-main/locations/global/keyRings/dyckshaus-keyring/cryptoKeys/sops
          created_at: "2024-01-22T23:29:51Z"
          enc: CiQA0oL7B4OMbPko7ugSJez6p+FvDxLOKkxffZDJamzvbXQB094SSQApFo36/RkbWjXMCQoTdzQCXnp3FA/XvsIj7RPMt1G402LsqKvzhWF6g+eJXGkSmBbSgFrTE+ajcfam2sOlvq30CRdZil0oK78=
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ay5dn0m46ya06gt2nwxk0mfcfvu2f3e66gadldnn3k06p7ys3gs25jfev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUW1KUWFUM2pxYW9PcVQv
            dnQ5S3ZiaWNiN2RDa1pzdDc1SVB5eHRYS0RjClZlRkF2MzE0VGw5bGQ0VlpXS2N4
            bm9DbnV1cTR0MDU2RnFteGNETktWQ3cKLS0tIHgzTnJDVVgyMXIwNXlvTGxNZ1RT
            S3RDVG9mNUp1bmNuU2N1LytCKzBJdzQKEidbAgJAFNfRCqu01cM29FJKAvG9+HK9
            SDq/mQEYXs1cV+Nnx2VzuBvQkqeKj/e5MuSBd4l1xdJX1tTYUbVIxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-22T23:29:52Z"
    mac: ENC[AES256_GCM,data:uvXQEHOjHm4JHo1N7fSfK8dJNHFxyej7THLfM345gIkeb/sIWckJRsOgg3v8WhzjJdx8vRVhIRMJt5WG6tFzZ/vtN0imFNkRwuL4a4GfKfuY0FOjdu+cWaLg+6svflkcXUPngcmPuxhL3QT3J95Lw5YzgUkmpWirXLN6dRkdYXw=,iv:rOqG/ovq7ox3ftYB0hVQB5gfVTu36QaffFyTmr2BWxQ=,tag:VXn4dmV/XC/hSzrRXAcPfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
